targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          explicit_to_json: true
          field_rename: snake
          include_if_null: false